### ISSUE TITLE
empty index.html

### ISSUE THREAD

**Issue by Rigel772** [joshnuss/materialize-svelte#1]
for some reason **npm run build** generates empty index.html...
what could be the problem?
thanks
oskar

**Comment by joshnuss** [comment]
Hi @Rigel772,

Does `npm run dev` work for you?

There is a file `public/index.html` that is in use.

**Comment by Rigel772** [comment]
strangely it does... :) however the slideshow is not working (pictures sit on top of each other)

**Comment by Rigel772** [comment]
I can see the table on localhost:5000 but still the index.html is with empty body:
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset='utf-8'>
	<meta name='viewport' content='width=device-width,initial-scale=1'>

	<title>Svelte app</title>

	<link rel='icon' type='image/png' href='/favicon.png'>
	<link rel='stylesheet' href='/build/base.css'>
	<link rel='stylesheet' href='/build/bundle.css'>

	<script defer src='/build/bundle.js'></script>
</head>

<body>
</body>
</html>

**Comment by Rigel772** [comment]
oh, I get it! the body is inserted by the app in browser!! silly me, forget it, sorry to bother you...
